# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7afe0becdf3908127dd9690a12416508496d69a42852dbee57cfc59b05ecf63583b00dd4e597b9ca60021c02a1a18272cd627aeba2a415d39dbcd02cd1930ffc

test:
  secret_key_base: 264657d36e9086d4c34eec5922c735ac8c986cf597a800b358e62fad1fbd3a86a80c342544a2fc6bd9f6034c84f4061dc94d75de1a750806f788111db5350000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
